# Generated by Django 2.0.2 on 2018-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180219_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rqst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('sender', models.IntegerField()),
            ],
        ),
    ]
