# Generated by Django 2.0.2 on 2018-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_rqst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rqst',
            name='receiver',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rqst',
            name='sender',
            field=models.CharField(max_length=300),
        ),
    ]
