# Generated by Django 2.0.2 on 2018-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20180220_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='state',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
