# Generated by Django 2.0.2 on 2018-08-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=300)),
                ('frm', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
