# Generated by Django 2.0.2 on 2018-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default='admin', max_length=300),
        ),
    ]
